name: Bazel

on:
  push:
    branches:
      - "**"
jobs:
  build_and_test_ubuntu20:
    name: Linux Ubuntu 20.04 build <GCC 9.3.0>
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-ubuntu20

      - name: Build
        run: |
          cd example
          bazelisk build //...
  build_and_test_ubuntu22:
    name: Linux Ubuntu 22.04 build <GCC 11.2.0>
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-ubuntu22

      - name: Build
        run: |
          cd example
          bazelisk build //...

  build_and_test_macos11:
    name: macOS 11 build <Apple Clang>
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-macos-11

      - name: Build
        run: |
          cd example
          bazelisk build //...

  build_and_test_macos12:
    name: macOS 12 build <Apple Clang>
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-macos-12

      - name: Build
        run: |
          cd example
          bazelisk build //...

  build_and_test_windows_2019:
    name: Windows 2019 <Visual Studio 2019>
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-windows-2019

      - name: Build
        run: |
          cd example
          bazelisk build //...

  build_and_test_windows_2022:
    name: Windows 2022 <Visual Studio 2022>
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-windows-2022

      - name: Build
        run: |
          cd example
          bazelisk build //...
